language: node_js
node_js:
  - "0.12"
  - "0.10"
script:
  - npm test --loglevel info
  - npm run build --loglevel info
after_success:
  - cd CAEkit
  - zip CAEkit-win32
  - ls -ltrph /home/travis/build/ccopsey/CAEkit