language: node_js
node_js:
  - "0.12"
  - "0.10"
script:
  - npm test --loglevel info
  - npm run build --loglevel info
after_success:
  - ls -ltrph /home/travis/build/ccopsey
  - ls -ltrph /home/travis/build/ccopsey/CAEkit
  - ls -ltrph /home/travis/build/ccopsey/CAEkit/CAEkit-win32